resources:
- deployment.yaml
configMapGenerator:
- name: service-configmap-files
  behavior: create
  files:
  - config-files/service-config.yaml
- name: service-config-env
  behavior: create
  literals:
  - SERVICE_CONFIG_FILE=config/service-config.yaml
  - SERVICE_RDBS_PORT=123
  - SERVICE_PORT=789
